#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-4 -d I II III IV V 
bspc monitor HDMI-0 -d VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           10
bspc config split_ratio          0.52
bspc config pointer_action1 move
bspc config pointer_motion_interval 7

. "${HOME}/.cache/wal/colors.sh"
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Resolution
#xrandr --output HDMI-0 --mode 1920x1080 --rate 60.00 --output DP-4 --mode 2560x1440 --rate 144.00 --primary --left-of HDMI-0

# Wallpaper
feh --bg-scale ~/big-stuff/pictures/leaf.png

# Polybar
$HOME/.config/polybar/launch.sh

# Dunst
/usr/bin/dunst
