#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# TODO: Add guide for multi-monitors
# bspc monitor DP-4 -d I II III IV V 
# bspc monitor HDMI-0 -d VI VII VIII IX X

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Old
# bspc config border_width         2
# bspc config window_gap           5
# bspc config split_ratio          0.52
# bspc config pointer_action1 move
# bspc config pointer_motion_interval 7

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Resolution
#xrandr --output Virtual1 --mode 1400x1050 --primary

# Wallpaper
#feh --bg-scale "$HOME/pictures/leaf.png"

# Polybar
# "$HOME"/.config/polybar/launch.sh

# Dunst
/usr/bin/dunst
