#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# TODO: Add guide for multi-monitors
# bspc monitor DP-4 -d I II III IV V 
# bspc monitor HDMI-0 -d VI VII VIII IX X

bspc monitor -d 一 二 三 四 五 六 七 八 九 十

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Old
# bspc config border_width         2
# bspc config window_gap           5
# bspc config split_ratio          0.52
# bspc config pointer_action1 move
# bspc config pointer_motion_interval 7

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

VBoxClient-all # TODO: Remove this when not doing virtualbox

# Resolution
xrandr --output Virtual-1 --mode 1400x1050 --primary # TODO: May not be needed with nvidia control panel

# Wallpaper
feh --bg-scale "$HOME/pictures/leaf.png"

# Polybar
"$HOME"/.config/polybar/launch.sh

# Dunst
/usr/bin/dunst &

# Session lock on sleep
xss-lock --transfer-sleep-lock -- i3lock --nofork &

# aa-notify -p -s 1 -w 60 -f /var/log/audit/audit.log # TODO: Verify this works
